version: '3.7'
services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
            MONGO_INITDB_DATABASE: nettu-meeting
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_nettumeet_container:/data/db
        logging:
            driver: none
    redis:
        image: redis
        ports:
            - 6379:6379
        logging:
            driver: none

volumes:
    mongodb_data_nettumeet_container:
